public class Subscription {
    public class StripeSubscription {
        public String Id;
        public String collection_method;
        public Integer created;
        public Integer current_period_end;
        public Integer current_period_start;
        public String customer;
        public Integer days_until_due;
        public String default_payment_method;
        public String latest_invoice;
        public String status;
    }
    public class StripeSubscriptionItem {
        
    }
}
